package com.smartlivestock.iot.domain.model;

/**
 * Identifies the source of telemetry data ingested into the system.
 */
public enum TelemetrySource {
    /** Polled from agentic-middle-platform via Feign report-record/page. */
    AGENTIC_PLATFORM,
    /** Generated by datagen synthetic data synthesis. */
    DATAGEN,
    /** Pushed via HTTP telemetry endpoint. */
    HTTP,
    /** Historical data backfilled via manual file import (NIX-79). */
    MANUAL_IMPORT
}
