package com.smartlivestock.shared.common;

public enum ErrorCode {
    OK,
    VALIDATION_ERROR,
    BAD_REQUEST,
    AUTH_TOKEN_EXPIRED,
    AUTH_INVALID_TOKEN,
    AUTH_API_KEY_INVALID,
    AUTH_API_KEY_EXPIRED,
    AUTH_FORBIDDEN,
    TENANT_DISABLED,
    QUOTA_EXCEEDED,
    LICENSE_EXPIRED,
    RESOURCE_NOT_FOUND,
    STATE_CONFLICT,
    DUPLICATE_RESOURCE,
    DEVICE_NOT_ACTIVE,
    RESOURCE_DELETED,
    FARM_SCOPE_CONFLICT,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_ERROR
}
