spring:
  datasource:
    url: jdbc:tc:postgresql:16:///smart_livestock_test
  jpa:
    hibernate:
      ddl-auto: validate
  autoconfigure:
    exclude:
      - org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration
