package com.smartlivestock.ranch.application.signal;

public enum SignalEventType {
    LIVESTOCK_POSITION_CHANGED,
    RUMEN_METRIC_CHANGED,
    ALERT_CHANGED,
    FENCE_SIGNAL_CHANGED,
    FENCE_GEOMETRY_CHANGED,
    HEALTH_SIGNAL_CHANGED,
    AI_ASSESSMENT_COMPLETED,
    DEVICE_SIGNAL_CHANGED,
    INSTALLATION_CHANGED,
    LIVESTOCK_CHANGED
}
