package com.smartlivestock.shared.security;

import com.smartlivestock.identity.domain.model.User;
import com.smartlivestock.identity.domain.repository.UserRepository;
import com.smartlivestock.shared.common.ApiException;
import com.smartlivestock.shared.common.ErrorCode;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.HandlerInterceptor;

import java.util.Set;

/**
 * NIX-191: accounts whose initial password was generated by someone else
 * (issuing tool / installer) carry {@code must_change_password}. Until the
 * password is replaced, every API except the allow-listed ones is rejected
 * with PASSWORD_CHANGE_REQUIRED so the client is forced into the
 * password-change flow.
 */
@Component
@RequiredArgsConstructor
public class PasswordChangeRequiredInterceptor implements HandlerInterceptor {

    /** Paths an un-migrated (must-change) account may still reach. */
    private static final Set<String> ALLOWED_PREFIXES = Set.of(
            "/api/v1/auth/",
            "/api/v1/me/password",
            "/api/v1/deployment-info",
            // first-certificate window endpoints stay reachable: the bootstrap
            // administrator may be born through them while carrying the flag
            "/api/v1/admin/deployment-license/"
    );
    private static final Set<String> ALLOWED_EXACT = Set.of(
            "/api/v1/me",
            "/api/v1/deployment-info",
            "/health"
    );

    private final UserRepository userRepository;

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response,
                             Object handler) {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null || !(authentication.getPrincipal() instanceof Long userId)) {
            return true; // anonymous — downstream auth rules apply
        }
        String uri = request.getRequestURI();
        if (ALLOWED_EXACT.contains(uri) || ALLOWED_PREFIXES.stream().anyMatch(uri::startsWith)) {
            return true;
        }
        User user = userRepository.findById(userId).orElse(null);
        if (user == null || !user.isMustChangePassword()) {
            return true;
        }
        throw new ApiException(ErrorCode.PASSWORD_CHANGE_REQUIRED, "error.passwordChangeRequired");
    }
}
