-- ============================================================
-- V20260907120000: Admin bootstrap support (NIX-191)
--
-- 1. users.must_change_password: set for accounts whose initial
--    password was generated by someone else (installer / issuing
--    tool); the account is locked to the password-change flow
--    until the password is replaced.
-- 2. Known seeded platform admins (V4 / V20260724100000, public
--    phone numbers with a public password):
--      - Deployments that already accepted a license keep the admin
--        but are forced through a password change on next login.
--      - Fresh installs (no license ever accepted) must not carry a
--        known credential at all: the account is deactivated and the
--        deployment administrator will be born from the first
--        accepted activation certificate instead.
--    Dev/test environments re-activate the demo admin through the
--    db/demo seed location (not loaded in release installs).
-- ============================================================

ALTER TABLE users ADD COLUMN must_change_password BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE users SET must_change_password = TRUE
WHERE role = 'PLATFORM_ADMIN'
  AND phone IN ('13800000000', '13700000000')
  AND EXISTS (SELECT 1 FROM deployment_licenses WHERE status = 'CURRENT');

UPDATE users SET is_active = FALSE
WHERE role = 'PLATFORM_ADMIN'
  AND phone IN ('13800000000', '13700000000')
  AND NOT EXISTS (SELECT 1 FROM deployment_licenses WHERE status = 'CURRENT');
